spring.application.name=hospital-patient-management

spring.datasource.url=jdbc:mysql://localhost:3306/hospital_manage
spring.datasource.username=root
spring.datasource.password=sHiv@#1234#@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
